# 12월 15일 월 복습
## Numpy & Pandas 기초

In [4]:
import numpy as np

In [6]:
# 리스트 생성
li1 = [1, 2.0, '3'] # 리스트는 다양한 자료형을 원소로 갖음
li1

[1, 2.0, '3']

In [8]:
# 리스트 변환
ar1 = np.array(object = li1) # 배열은 원소 자료형을 통일 시킴. (정수->실수->문자열)
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [9]:
# 클래스 확인
type(ar1) 

numpy.ndarray

In [10]:
# 차원 확인
ar1.ndim # 배열의 차원을 반환

1

In [11]:
# 형태 확인
ar1.shape # axis가 0인 축의 원소 개수를 튜플로 반환

(3,)

In [12]:
# 원소 개수 확인
ar1.size # 1차원 배열의 size 속성은 전체 원소 개수를 정수로 반환

3

In [13]:
# 원소 자료형 확인
ar1.dtype 

dtype('<U32')

In [14]:
# 원소 자료형을 정수로 변환
ar1.astype(dtype = int) # 두번쩨 원소인 '2.0' 때문에 에러를 일으킴

ValueError: invalid literal for int() with base 10: np.str_('2.0')

In [15]:
# 원소 자료형을 실수로 변환
ar1.astype(dtype = float) # astype 메서드는 실행 결과를 배열롤 반환

array([1., 2., 3.])

In [ ]:
# 원소 자료형을 실수로 변환한 결과(배열)에 이어서 정수로 변환
ar1.astype(dtype = float).astype(dtype = int) # 이런 코딩 방식을 method chaining이라 함

In [18]:
# 모든 원소에서 소수점 이하를 버리고 문자열로 변환
ar1.astype(dtype = float).astype(dtype = int).astype(dtype = str)

array(['1', '2', '3'], dtype='<U21')

In [ ]:
# 배열을 생성할 때 원소 자료형 지정
np.array(object = li1, dtype = int) # 배열을 자료형 정수로 지정
np.array(object = li1, dtype = float) # 실수로 지정
np.array(object = li1, dtyper = str) # 문자열로 지정 
np.array(object = li1, dtype = object) # 객체로 지정 

In [19]:
# 간격이 일정한 배열 생성
# 0부터 5까지 연속하는 정수형 배열을 반환
np.arange(6) 

array([0, 1, 2, 3, 4, 5])

In [20]:
# 1 이상 6 미만 # step 지정 안하면 자동 1 간격
np.arange(start = 1, stop = 6) 

array([1, 2, 3, 4, 5])

In [21]:
 # 1부터 5까지 간격이 2인 정수형 배열 반환
np.arange(start = 1, stop = 6, step = 2) 

array([1, 3, 5])

In [22]:
# 0부터 1까지 간격이 0.1인 실수형 배열 반환
np.arange(start = 0, stop = 1, step = 0.1) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [26]:
# 전체를 n개로 등분하는 (n+1개의 원소를 갖는) 1차원 배열을 생성
# 0~1을 10등분하는 실수형 배열 반환, 끝값 포함
np.linspace(start = 0, stop = 1, num = 10+1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
# 80~75를 30등분하는 실수형 배열을 반환
np.linspace(start = 80, stop = 75, num = 30+1) 

array([80.        , 79.83333333, 79.66666667, 79.5       , 79.33333333,
       79.16666667, 79.        , 78.83333333, 78.66666667, 78.5       ,
       78.33333333, 78.16666667, 78.        , 77.83333333, 77.66666667,
       77.5       , 77.33333333, 77.16666667, 77.        , 76.83333333,
       76.66666667, 76.5       , 76.33333333, 76.16666667, 76.        ,
       75.83333333, 75.66666667, 75.5       , 75.33333333, 75.16666667,
       75.        ])

In [32]:
# 원소를 반복한 배열 생성
# ar1의 전체 원소를 두 번 반복한 배열을 반환
np.tile(A = ar1, reps = 2) 
## 대문자 A는 관례임. 
## np.tile(ar1, 2) 사용가능

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [33]:
# ar1의 각 원소를 두 번씩 반복한 배열을 반환
np.repeat(a = ar1, repeats = 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [34]:
# ar1의 각 원소별로 지정한 횟수를 반복한 배열을 반환
np.repeat(a = ar1, repeats = [3, 2, 1])

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

# 다음 시간 예습
## 인덱싱

### 1차원 배열 기본 인덱싱

In [41]:
# 1부터 11까지 홀수를 원소로 갖는 1차원 배열을 생성
ar1 = np.arange(start = 1, stop = 12, step = 2)
ar1

array([ 1,  3,  5,  7,  9, 11])

In [42]:
# 대괄호 안에 정수 인덱스(위치번호)를 지정하면 해당 원소를 반환.(인덱싱)
ar1[0]

np.int64(1)

In [43]:
ar1[1]

np.int64(3)

In [44]:
ar1[2]

np.int64(5)

In [45]:
ar1[-1]

np.int64(11)

### 슬라이싱

In [47]:
# 대괄호 안에 시작과 끝 인덱스를 콜론(:)으로 연결한 슬라이스를 지정하면 연속하는 원소를 선택한 배열을 반환.
# 끝 인덱스를 포함하지 않으므로 끝 인덱스 +1 값을 지정해야 함. (시작:끝+1)
ar1[0:3] # o번째 ~ 3-1 = 2번쨰 인덱스 위치에 있는 값 반환.

array([1, 3, 5])

In [48]:
ar1[:3] # 0번째 인덱스 부터 2번째 인덱스까지

array([1, 3, 5])

In [49]:
ar1[3:] # 3번째 인덱스 부터 끝까지

array([ 7,  9, 11])

In [50]:
ar1[:] 첫번째 인덱스 값 부터 마지막 원소까지 모두 반환. (깊은 복사)

array([ 1,  3,  5,  7,  9, 11])

### 1차원 배열 고급 인덱싱

In [52]:
# 배열의 3번, 1번, 2번 인덱스 원소를 차례대로 선택하여 배열로 반환
ar1[[3, 1, 2]] 

array([7, 3, 5])

In [53]:
# 3번 인덱스 원소를 세 번 선택하여 배열로 반환
ar1[[3, 3, 3]]

array([7, 7, 7])

In [54]:
# True 위치의 원소를 배열로 반환. (불리언 인덱싱)
ar1[[False, False, False, True, True, True]]

array([ 7,  9, 11])

In [55]:
# 조건식을 만족하는 원소를 배열로 반환.
ar1[ar1 >= 7] 

array([ 7,  9, 11])

### 2차원 배열 생성

In [58]:
# 같은 길이의 리스트를 원소로 갖는 리스트를 생성
li2 = [[1, 3, 5], [7, 9, 11]]
li2

[[1, 3, 5], [7, 9, 11]]

In [59]:
# 리스트를 2차원 배열로 반환
ar2 = np.array(object = li2)
ar2 

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [60]:
# ar2의 클래스를 확인 
type(ar2) 

numpy.ndarray

### 2차원 배열 확인

In [61]:
# ar2의 차원을 확인
ar2.ndim 

2

In [62]:
# ar2의 형태를 확인 # (행, 열) # axis가 0과 1인 축의 원소 개수를 튜플로 반환
ar2.shape

(2, 3)

In [63]:
# ar2의 원소 개수를 확인 # 행 x 열
ar2.size

6

In [64]:
# ar2의 원소 자료형을 확인
ar2.dtype 

dtype('int64')

### 배열의 재구조화
#### 1차원 배열을 2차원 배열로 변환

In [65]:
# 2행 3열인 2차원 배열로 변환. # 행 X 열의 약수만 가능 
ar1.reshape(2,3) 
# reshape는 모양만 바뀌고 본질은 그대로. ## 총 원수 갯수가 6개니까 6의 약수로 행열 구성이 가능하단 뜻.

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [66]:
# 매개변수에 'F'를 지정하면 원소 입력 방향을 세로로 변경. (기본값: 'C')
ar1.reshape(2, 3, order = 'F')

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [71]:
# ar1을 2행 3열인 2차원 배열로 변환하고 ar2에 할당.
# 열 위치에 -1을 지정하면 행 개수로 열 개수를 자동 계산.
ar2 = ar1.reshape(2, -1)
ar2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

#### 2차원 배열을 1차원 배열로 변환

In [73]:
# ar2의 원소를 가로 방향으로 펼친 1차원 배열로 변환. (깊은 복사)
# order 매개변수에 원소 입력 방향을 지정. (기본값: 'C')
ar2.flatten()

array([ 1,  3,  5,  7,  9, 11])

In [74]:
# ar2의 원소를 가로 방향으로 펼친 1차원 배열로 변환.
# flatten 메서드는 깊은 복사, ravel 메서드는 얕은 복사를 실행. 
ar2.ravel()

array([ 1,  3,  5,  7,  9, 11])

#### 2차원 배열 인덱싱 및 슬라이싱

In [75]:
# 2차원 배열은 대괄호 안에 콤마를 추가하고 행/열 인덱스를 차례대로 지정.
# ar2의 1행, 1열 원소를 선택
ar2[0, 0] 

np.int64(1)

In [76]:
# ar2의 1행을 선택. ar2[0, :] 
ar2[0]

array([1, 3, 5])

In [78]:
# 2차원 배열로 슬라이싱
# ar2의 1~2행, 1~2열을 선택
ar2[0:2, 0:2] 

array([[1, 3],
       [7, 9]])

In [79]:
# ar2의 전체 행, 2~3열 선택
# 빔 콜론은 전체 행 또는 열을 선택함
ar2[:, 1:3] 

array([[ 3,  5],
       [ 9, 11]])

In [80]:
# 2차원 배열로 팬시 인덱싱
ar2[:, [2, 1]]

array([[ 5,  3],
       [11,  9]])